[package]
name = "veyra-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Veyra GTK4 + Libadwaita user interface: windows, views, widgets."

[dependencies]
veyra-core = { path = "../veyra-core" }
veyra-filesystem = { path = "../veyra-filesystem" }
veyra-search = { path = "../veyra-search" }
tracing.workspace = true
chrono.workspace = true
gtk4 = { version = "0.9", package = "gtk4" }
libadwaita = { version = "0.7", features = ["v1_5"] }
gio = "0.20"
glib = "0.20"
async-channel = "2"
